#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#        see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: no-reply@schoddle.com
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          # NOTE: make sure that this is the hosted Zone ID for
          # for the environment domain.
          route53:
            region: ap-south-1
            hostedZoneID: Z01622221BW021ZOGMKQF

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-openedx-prod-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: courses.schoddle.com
  dnsNames:
    - "*.courses.schoddle.com"
